# Generated by Django 4.2.13 on 2024-05-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('price', models.CharField(max_length=255, verbose_name='Item Price')),
                ('description', models.CharField(max_length=255, verbose_name='Item Description')),
            ],
        ),
    ]
