# Generated by Django 4.2.13 on 2024-05-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='price',
            field=models.IntegerField(max_length=255, verbose_name='Item Price'),
        ),
    ]
